%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

Name:           ros-jazzy-openvdb-vendor
Version:        2.5.4
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS openvdb_vendor package

License:        LGPL v2.1 and MPL-2.0 license
URL:            https://github.com/AcademySoftwareFoundation/openvdb
Source0:        %{name}-%{version}.tar.gz

Requires:       blosc-devel
Requires:       boost-devel
Requires:       openvdb-devel
Requires:       tbb-devel
Requires:       zlib-devel
Requires:       ros-jazzy-ros-workspace
BuildRequires:  blosc-devel
BuildRequires:  boost-devel
BuildRequires:  git
BuildRequires:  openvdb-devel
BuildRequires:  ros-jazzy-ament-cmake
BuildRequires:  ros-jazzy-ament-cmake-vendor-package
BuildRequires:  tbb-devel
BuildRequires:  zlib-devel
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Wrapper around OpenVDB, if not found on the system, will compile from source

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/jazzy" \
    -DAMENT_PREFIX_PATH="/opt/ros/jazzy" \
    -DCMAKE_PREFIX_PATH="/opt/ros/jazzy" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/jazzy

%changelog
* Fri Dec 13 2024 Tim Clephas <tim.clephas@nobleo.nl> - 2.5.4-1
- Autogenerated by Bloom

* Wed Nov 06 2024 Tim Clephas <tim.clephas@nobleo.nl> - 2.5.3-1
- Autogenerated by Bloom

* Fri Aug 30 2024 Tim Clephas <tim.clephas@nobleo.nl> - 2.5.2-1
- Autogenerated by Bloom

* Fri Aug 23 2024 Tim Clephas <tim.clephas@nobleo.nl> - 2.5.1-1
- Autogenerated by Bloom

* Wed Jul 17 2024 Tim Clephas <tim.clephas@nobleo.nl> - 2.5.0-1
- Autogenerated by Bloom

