Name:           ros-melodic-spatio-temporal-voxel-layer
Version:        1.3.5
Release:        2%{?dist}
Summary:        ROS spatio_temporal_voxel_layer package

Group:          Development/Libraries
License:        LGPL v2.1
Source0:        %{name}-%{version}.tar.gz

Requires:       OpenEXR-devel
Requires:       openvdb
Requires:       openvdb-devel
Requires:       ros-melodic-costmap-2d
Requires:       ros-melodic-dynamic-reconfigure
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-laser-geometry
Requires:       ros-melodic-message-filters
Requires:       ros-melodic-pcl-conversions
Requires:       ros-melodic-pcl-ros
Requires:       ros-melodic-pluginlib
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-tf2-geometry-msgs
Requires:       ros-melodic-tf2-ros
Requires:       ros-melodic-visualization-msgs
Requires:       tbb-devel
BuildRequires:  OpenEXR-devel
BuildRequires:  openvdb
BuildRequires:  openvdb-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-costmap-2d
BuildRequires:  ros-melodic-dynamic-reconfigure
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-laser-geometry
BuildRequires:  ros-melodic-message-filters
BuildRequires:  ros-melodic-message-generation
BuildRequires:  ros-melodic-pcl-conversions
BuildRequires:  ros-melodic-pcl-ros
BuildRequires:  ros-melodic-pluginlib
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-tf2-geometry-msgs
BuildRequires:  ros-melodic-tf2-ros
BuildRequires:  ros-melodic-visualization-msgs
BuildRequires:  tbb-devel

%description
The spatio-temporal 3D obstacle costmap package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Thu Jul 18 2019 Steve Macenski <stevenmacenski@gmail.com> - 1.3.5-2
- Autogenerated by Bloom

* Thu Jul 18 2019 Steve Macenski <stevenmacenski@gmail.com> - 1.3.5-1
- Autogenerated by Bloom

* Wed Jul 17 2019 Steve Macenski <stevenmacenski@gmail.com> - 1.3.4-1
- Autogenerated by Bloom

* Fri Jul 12 2019 Steve Macenski <stevenmacenski@gmail.com> - 1.3.3-3
- Autogenerated by Bloom

* Fri Jul 12 2019 Steve Macenski <stevenmacenski@gmail.com> - 1.3.3-2
- Autogenerated by Bloom

* Fri Jul 12 2019 Steve Macenski <stevenmacenski@gmail.com> - 1.3.3-1
- Autogenerated by Bloom

